config/routes.rb
FinalProject::Application.routes.draw do

  root 'home#index'

  get '/auth/:provider/callback'  => 'sessions#create'
  post '/signin'                  => 'sessions#new',         :as => :signin
  delete '/signout'               => 'sessions#destroy',     :as => :signout
  get '/auth/failure'             => 'sessions#failure'

  get '/users'                    => 'users#show_all'
  get '/available'                => 'users#set_available',  :as => :set_available               
  get '/user/:github_username'    => 'users#show_details',   :as => :show_details
  get '/edit'                     => 'users#edit_details',   :as => :edit
  patch '/users'                  => 'users#update_details', :as => :update
  get '/admin'                    => 'users#admin',          :as => :admin
  get '/admin/:username'          => 'users#confirm',        :as => :confirm

end

app/models/github.rb
require 'open-uri'

class Github
  def initialize username
    @username = username
  end

  attr_reader :username
  
  
  def stats_uri
    "https://api.github.com/users/#{username}"
  end

  def repos_uri
    statistics[:repos_url]
  end

  def cv_uri
    cv_repo = repos.find { |repo| repo[:name] == 'CV' }
    cv_repo[:contents_url].gsub('{+path}', 'README.md') if cv_repo
  end

  def repos 
    fetch_json(repos_uri)
  end

  def statistics 
    fetch_json(stats_uri)
  end

  def cv_plain
    return "" unless cv_uri
    encoded = fetch_json(cv_uri)[:content]
    Base64.decode64(encoded)
  end

  def cv_html
    markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML, :autolink => true, :space_after_headers => true)
    markdown.render(cv_plain)
  end

  def fetch_json uri
    raw_data = open(uri).read
    JSON.parse(raw_data, :symbolize_names => true)
  end

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id               :integer          not null, primary key
#  provider         :string(255)
#  uid              :string(255)
#  name             :string(255)
#  oauth_token      :string(255)
#  oauth_expires_at :datetime
#  created_at       :datetime
#  updated_at       :datetime
#  email            :string(255)
#  verified_maker   :boolean          default(FALSE)
#  github_username  :string(255)
#  profile_image    :string(255)
#  cohort           :string(255)
#  seeking_work     :datetime
#  admin            :boolean          default(FALSE)
#  bio              :string(255)
#  twitter          :string(255)
#  linkedin         :string(255)
#

class User < ActiveRecord::Base

  validates :github_username, presence: true
  validates :uid,             presence: true
  validates :provider,        presence: true

  def self.create_with_omniauth(auth)
    where(auth.slice(:provider, :uid)).first_or_initialize.tap do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.github_username = auth.info.nickname
      user.profile_image = auth.extra.raw_info.avatar_url
      user.email = auth.info.email
      user.name = auth.info.name
      user.oauth_token = auth.credentials.token
      # user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      user.save!
    end
  end

  def confirm_maker
    self.verified_maker = true
    save!
  end

  def make_admin
    self.admin = true
    save!
  end

  def set_as_available
    self.seeking_work = Time.new
    save!
  end

  def set_as_unavailable
    self.seeking_work = nil
    save!
  end

  def seeking_work?
    (seeking_work || Time.new(1970)) > Time.now - 2.weeks
  end

  def self.verified_makers
    User.where(verified_maker: true)
  end

  def self.makers_seeking_work
    User.all.select{ |user| user.seeking_work? }
  end

  def github
    Github.new(github_username)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
 
  helper_method :current_user
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	@user = User.verified_makers.sample
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
      auth = request.env["omniauth.auth"]
      # ap auth
      user = User.where(:provider => auth['provider'], :uid => auth['uid'].to_s).first || User.create_with_omniauth(auth)
      reset_session
      session[:user_id] = user.id
      redirect_to root_url
    end

    def destroy
      reset_session
      redirect_to root_url, :notice => 'Signed out!'
    end

    def failure
      redirect_to root_url, :alert => "Authentication error: #{params[:message].humanize}"
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show_all
    @users = (current_user && current_user.admin?) ? User.all : User.verified_makers
    @users.shuffle!
  end

  def show_details
  	@showcase_user = User.find_by_github_username(params['github_username'])
    @user = current_user
    gon.github_username = @showcase_user.github_username if @showcase_user
    if @showcase_user && @showcase_user.stackoverflow
      id = @showcase_user.stackoverflow.match(/\d+/)[0]
      gon.stackoverflow_id = id
    end
    redirect_to root_path, alert: 'User profile not found' unless @showcase_user
  end

  def edit_details
  	@user = current_user
    redirect_to root_path, alert: 'You must be logged in to edit profile' unless @user
  end

  def update_details
    @user = current_user
    @user.update_attributes(user_params)
    redirect_to edit_path, notice: 'Updates saved'
  end

  def admin
    @user = current_user
    redirect_to root_path, alert: 'You must have admin privilages to view admin' unless (@user && @user.admin)
  end

  def confirm
    @user_to_be_confirmed = User.find_by_github_username(params[:username])
    @user_to_be_confirmed.confirm_maker if current_user && current_user.admin?
    redirect_to '/users', notice: "#{@user_to_be_confirmed.github_username} is now a verified maker!"
  end

  def set_available
    if current_user.seeking_work?
      current_user.set_as_unavailable
    else
      current_user.set_as_available
    end
    redirect_to '/edit', notice: 'You have successfully updated your work availability status!'
  end
  private

  def user_params
    params.require(:user).permit(:name, :email, :profile_image, :cohort, :bio, :twitter, :linkedin, :stackoverflow, :website, :blog)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<div class="row shadow">
  <div class="medium-12 columns" role="content">
    <article>
      <p class="centre em"><strong>The showcase for graduates of <a target="_blank" href="http://www.makersacademy.com/"> Makers Academy</strong></a> 
        
      </p>
      <hr />
    </article>
  </div>

  <div class="large-12 columns">
    <div class="large-7 columns">
    <% if @user %> 
      <div>
        <h3><%= link_to @user.name, show_details_path(@user.github_username) %> 
          <small style="text-align:right;"> is just one example, you can get a <a style="text-align:right;font-size: 20px;" href='/users'>full list.</a></small></h3>
          <!-- <a style="float:right;" class='button' href='/users'>List All Makers</a> -->
      </div>


      <div class="user-image">  

        <%= link_to image_tag(@user.profile_image, width: '70%', ), show_details_path(@user.github_username) %>
      </div>

        <p><%= @user.bio %></p>
        <hr />
        <p>If you are a prospective employer or for any other reason you want to
          contact anyone you see here, please email  <a href="mailto:ruben@makersacademy.com">Ruben Kostucki</a>
        </p>
        <a class='button' href='/users'>Full list</a>

    <% end %>
  </div>

  <div class="large-5 columns"> 
    <h3>Technologies</h3><p><em>Full-stack</em> training means learning both the client-facing and back-end elements of web development. </p>

      <ul class="no-bullet">
        <li><%= content_tag(:i, nil, class: 'icon-ruby') %>Ruby</li>
        <li><%= content_tag(:i, nil, class: 'icon-ruby-on-rails') %>Ruby  with both Sinatra and Rails</li>
        <li><%= content_tag(:i, nil, class: 'icon-google-developers') %>Object Oriented Programming</li>
        <li><%= content_tag(:i, nil, class: 'icon-heroku') %>Git & Heroku</li>
        <li><%= content_tag(:i, nil, class: 'icon-html') %>HTTP, HTML & CSS</li>
        <li><%= content_tag(:i, nil, class: 'icon-javascript') %>JavaScript, Ajax & Jquery</li>
        <li><%= content_tag(:i, nil, class: 'icon-css') %>Haml, SASS & CoffeeScript</li>
        <li><%= content_tag(:i, nil, class: 'icon-osx') %>Unix OS</li>
        <li><%= content_tag(:i, nil, class: 'icon-shell') %>Text editors</li>
        <li><%= content_tag(:i, nil, class: 'icon-postgres') %>Postgresql</li>
        <li><%= content_tag(:i, nil, class: 'icon-microscope') %>Capybara, Cucumber & RSpec</li>
        <li><%= content_tag(:i, nil, class: 'icon-line-graph') %>Test Driven Development</li>
        <li><%= content_tag(:i, nil, class: 'icon-database') %>BCrypt</li>
        <li><%= content_tag(:i, nil, class: 'icon-aws') %>Amazon Web Services</li>
      </ul>
  </div>


  </div>
</div> 

app/views/layouts/_details.html.erb
<ul class="no-bullet medium-offset-2 medium-10">
  <li><%= content_tag(:i, nil, class: 'fi-mail') + mail_to(@showcase_user.email, @showcase_user.email) unless @showcase_user.email.blank? %></li>
  <li><%= content_tag(:i, nil, class: 'fi-social-github') + link_to(@showcase_user.github_username, "http://www.github.com/#{@showcase_user.github_username}") unless @showcase_user.github_username.blank? %></li>
  <li><%= content_tag(:i, nil, class: 'fi-social-twitter') + link_to(@showcase_user.twitter, "http://www.twitter.com/#{@showcase_user.twitter}") unless @showcase_user.twitter.blank? %></li>
  <li><%= content_tag(:i, nil, class: 'fi-social-linkedin') + link_to(@showcase_user.linkedin, 'http://'+@showcase_user.linkedin) unless @showcase_user.linkedin.blank? %></li>
  <li><%= content_tag(:i, nil, class: 'fi-social-stack-overflow') + link_to(@showcase_user.stackoverflow, 'http://'+@showcase_user.stackoverflow) unless @showcase_user.stackoverflow.blank? %></li>
  <li><%= content_tag(:i, nil, class: 'fi-web') + link_to(@showcase_user.website, 'http://'+@showcase_user.website) unless @showcase_user.website.blank? %></li>
  <li><%= content_tag(:i, nil, class: 'fi-quote') + link_to(@showcase_user.blog, 'http://'+ @showcase_user.blog) unless @showcase_user.blog.blank? %></li>
</ul>

app/views/layouts/_footer.html.erb
<footer class="row shadow">
    <ul class="inline-list">
      <li>Creative team:</li>
      <li><%= link_to "Rolando Barbella", show_details_path("Rolando-Barbella") %></li>
      <li><%= link_to "Mihai Cojocar", show_details_path("MihaiLiviuCojocar") %></li>
      <li><%= link_to "Colin Frankish", show_details_path("ColinFrankish") %></li>
      <li><%= link_to "Roy Gardiner", show_details_path("Roy-Gardiner") %></li>
      <li><%= link_to "Nabin Rai", show_details_path("nabin369") %></li>
      <li><%= link_to "Peter Saxton", show_details_path("CrowdHailer") %></li>
    </ul>
</footer>

app/views/layouts/_header.html.erb
<div class="row shadow">
  <div class="large-12 columns header">
    <div class="nav-bar right">
      <ul class="button-group">
        <% if current_user %>
          <li>
            <%= link_to 'My Profile', show_details_path(current_user.github_username), :class => "button" %>  
          </li>
          <li>
            <%= link_to 'Sign Out', signout_path, method: :delete, :class => "button github_button" %>
          </li>
        <% else %>
          <li><a href="https://github.com/login/oauth/authorize?scope=user:email&client_id=<%= ENV['GITHUB_CLIENT_ID'] %>" class="button">Sign in with Github</a></li>
        <% end %>
      </ul>
    </div>
    <h1><%= link_to 'Full Stack People', root_path %></h1>
  </div>
</div>
<% flash.each do |name, msg| -%>
  <%= content_tag :div, msg, class: ("#{name} row") %>
<% end -%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title><%= content_for?(:title) ? yield(:title) : "Full Stack People" %></title>
    <%= stylesheet_link_tag "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="assets/font-mfizz-1.2/font-mfizz.css">
  </head>
  <body>
    <%= render 'layouts/header' %>
    <%= yield %>
    <%= javascript_include_tag "application" %>
    <%= include_gon %>
    <script type="text/javascript" src="http://gitcv.herokuapp.com/fetchcv.js"></script>
    <script type="text/javascript" src="http://arcane-springs-5149.herokuapp.com/fetchdetails.js"></script>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/users/edit_details.html.erb
<div class="row shadow">
  <div class="medium-12 columns" role="content">
		<%= 'You are not yet confirmed as a maker' unless @user.verified_maker %>
    <h3>Update <%= @user.name %> <small><%= @user.github_username %> </small></h3>
    <div class="row">
      <div class="medium-6 columns">
        <%= image_tag @user.profile_image %>
      </div>
      <div class="medium-6 columns">
        <p class="bio">Bio</p>
        <%= @user.bio %>
      </div>
      <%= link_to 'Available For Work', set_available_path, :class => "button" unless @user.seeking_work? %>
      <%= link_to 'Not Available For Work', set_available_path, :class => "button" if @user.seeking_work? %>
    </div>
    <p> &nbsp; </p>
    <%= 'Updates saved' if @saved %>
		<%= form_for(@user, url: { action: "update_details" }) do |f| %>
			Email: <%= @user.email %><%= f.text_field :email %><br>

      Cohort: <%= @user.cohort %><%=
      f.select :cohort, [['November 2013'],['January 2014'],
                         ['February 2014'], ['March 2014'],
                         ['May 2014'],     ['June 2014'],
                         ['August 2014'],  ['September 2014'],
                         ['October 2014'], ['December 2014'],
                         ['February 2015'],
                         ['none']] %>
      Bio: <%= f.text_area  :bio, :maxlength=>"250", :rows=>"6"%><br>
      Profile image: <%= f.text_field :profile_image %><br>
      Twitter: <%= @user.twitter %><%= f.text_field :twitter %><br>
      Linkedin: <%= @user.linkedin %><%= f.text_field :linkedin %><br>
      Stackoverflow: <%= @user.stackoverflow %><%= f.text_field :stackoverflow %><br>
      Website: <%= @user.website %><%= f.text_field :website %><br>
      Blog: <%= @user.blog %><%= f.text_field :blog %><br>
      <%= f.submit 'Save', :class => 'button  submit' %>
		<% end %>
  </div>
</div>

app/views/users/show_all.html.erb
<div class="row shadow">
  <div class="medium-12 columns ">
  </div>
  <input id="myButton1" class='button' onclick="javascript:change()" type='button' value="Show makers seeking work"></input>
  <% @users.each do |user| %>
    <% available = user.seeking_work? ? 'available' : 'unavailable' %>
    <div class="medium-12 columns <%=available%>" >
    	<hr/>
      <div class="medium-3 columns " >
        <%= link_to image_tag(user.profile_image), show_details_path(user.github_username) %>
      </div>
      <div class="medium-9 columns" >
    		<h1><%= link_to user.name, show_details_path(user.github_username) %><small> <%= content_tag(:i, nil, class: 'fi-torsos-all') + user.cohort %>
          <%= content_tag(:span, 'Seeking Work', id: 'available_work', class: 'right') if user.seeking_work? %>
        </small>
        </h1>
        <p><%= user.bio %></p>
        <% @showcase_user = user %>
        <%= render 'layouts/details' %>
    	</div>
    </div>
  <% end %>
</div>

app/views/users/show_details.html.erb
<div class="row shadow">
  <div class="medium-12 columns" role="content">
    <div class="row">
      <div class="medium-4 columns detail_image" >
        <%= image_tag @showcase_user.profile_image, width:"300px"%>
      </div>
      <div class="medium-7 medium-offset-1 columns">
        <h1><%= @showcase_user.name %>
          <small>
            <%= content_tag(:i, nil, class: 'fi-torsos-all') + @showcase_user.cohort if @showcase_user.cohort %>
          <%= content_tag(:span, 'Seeking Work', id: 'available_work', class: 'right') if @showcase_user.seeking_work? %>
          </small>
        </h1>
        <p><%= @showcase_user.bio %></p>
        <%= render 'layouts/details' %>
        <%= link_to 'Back To Users', users_path, :class => "button" %>
        <% if current_user == @showcase_user %>
          <%= link_to 'Edit', edit_path, :class => "button" %>
        <% end %>
        <% if @user &&  @user.admin? && !@showcase_user.verified_maker? %>
          <%= link_to "Confirm maker", confirm_path(@showcase_user.github_username), :class => "button" %>
        <% end %>
      </div>
    </div>
    <article id="cv-service-container"></article>
    <article id="stackoverflow-details-container"></article>
  </div>
</div>